### ISSUE TITLE
Button problems on Chrome for Android.

### ISSUE THREAD

**Issue by neoone256** [mrjasonweaver/flexnav#78] opened 2013-09-19 16:34 UTC
Hello. I am using the most recent version of this plugin, it is great but I have notice that it has problems when using Chrome on Android. In my fixed position header, when you scroll the button comes later like if it were lazy... You scroll up and the button stays a bit down for a second. I would also call it a jump, maybe. I hope this works

**Comment by mrjasonweaver** [comment] 2013-10-01 01:21
Can't reproduce. Closing

**Closed as completed by mrjasonweaver** 2013-10-01 01:21 UTC
