### ISSUE TITLE
Menu item sub item closes menu and reloads current page

### ISSUE THREAD

**Issue by dheian** [mrjasonweaver/flexnav#71] opened 2013-09-03 19:04 UTC
Testing my FlexNav 1.1 usage at http://www.digitalhit.com/movies/reviews/in-a-world-2013/

Testing in Firefox and had a friend test with a Samsung Galaxy.

In small screen mode, I click on the menu bar, then if I click on a solo item, say, Awards Shows, it goes to the new page. But if I click on an item with a sub item and then click the sub item (say Movies>Movie Coverage Hub) the menu snaps shut and reloads the page we're already on instead of going to the new one.

Have also noticed that tabs with sub items will sometimes drop down in large screen mode and stay down.

**Comment by dheian** [comment] 2013-09-04 05:06
Been looking at this tonight and came across this. If a person hits the down arrow to reveal the submenu the submenu item works just fine. If they hit in an area outside of the arrow, the subitems will drop down but the browser will also load the blank "a href" of the top level item. Since people don't always hit right on the arrow should its touch area cover the full width of the top level item?

**Comment by mrjasonweaver** [comment] 2013-10-01 01:30
Can't reproduce at http://jasonweaver.name/lab/flexiblenavigation/ . Closing.

**Closed as completed by mrjasonweaver** 2013-10-01 01:30 UTC
